# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: pub
    open-pull-requests-limit: 0
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gradle
    open-pull-requests-limit: 0
    directory: /android
    schedule:
      interval: weekly
    groups:
      agp:
        patterns:
          - "com.android.*"

  - package-ecosystem: github-actions
    open-pull-requests-limit: 5
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - '*'